name: 'Code Quality'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: 'Lint'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: . -> target

      - name: Install additional problem matchers
        run: echo "::add-matcher::.github/problem-matchers.json"

      - name: Check formatting
        id: fmt
        run: cargo fmt --all -- --check
        continue-on-error: true

      - name: Run clippy
        id: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        continue-on-error: true

      - name: Build
        id: build
        run: cargo build --all-features
        continue-on-error: true

      - name: Run tests
        id: test
        run: cargo test --all-features
        continue-on-error: true

      - name: Check for lint results
        run: |
          echo "Checking outcomes of all steps..."
          if [[ "${{ steps.fmt.outcome }}" == "failure" || \
                "${{ steps.clippy.outcome }}" == "failure" || \
                "${{ steps.build.outcome }}" == "failure" || \
                "${{ steps.test.outcome }}" == "failure" ]]; then
            echo "One or more lints failed."
            exit 1
          else
            echo "All steps succeeded."
          fi
