[settings]
auto_install = false

[tools]
act = "0.2.84"
age = "1.3.1"
bun = "1.3.8"
cosign = "3.0.4"
gh = "2.86.0"
ghalint = "1.5.5"
pinact = "3.8.0"
slsa-verifier = "2.7.1"
sops = "3.11.0"
zizmor = "1.22.0"

[env]
_.file = ".config/local/.credentials.enc.yaml"
SOPS_CONFIG = ".config/local/.sops.yaml"


